CC = gcc

PROGRAMS = dup_1 dup_2 test test_2 fcntl_1 fopen_1 freopen_1 fdopen_1 ungetc_1 fputs_1 fread_1 ftell_1 fseek_1 frewind_1 fgetpos_1 feof_1 tmpfile_1 setbuf_1 fflush_1 vprintf_1

all: $(PROGRAMS)

dup_1: dup_1.c
	$(CC) -Wall -o $@ $^

dup_2: dup_2.c
	$(CC) -Wall -o $@ $^

test: test.c
	$(CC) -Wall -o $@ $^

test_2: test_2.c
	$(CC) -Wall -o $@ $^

fcntl_1: fcntl_1.c
	$(CC) -Wall -o $@ $^

fopen_1: fopen_1.c
	$(CC) -Wall -o $@ $^

freopen_1: freopen_1.c
	$(CC) -Wall -o $@ $^

fdopen_1: fdopen_1.c
	$(CC) -Wall -o $@ $^

ungetc_1: ungetc_1.c
	$(CC) -Wall -o $@ $^

fputs_1: fputs_1.c
	$(CC) -Wall -o $@ $^

fread_1: fread_1.c
	$(CC) -Wall -o $@ $^

ftell_1: ftell_1.c
	$(CC) -Wall -o $@ $^

fseek_1: fseek_1.c
	$(CC) -Wall -o $@ $^

frewind_1: frewind_1.c
	$(CC) -Wall -o $@ $^

fgetpos_1: fgetpos_1.c
	$(CC) -Wall -o $@ $^

feof_1: feof_1.c
	$(CC) -Wall -o $@ $^

tmpfile_1: tmpfile_1.c
	$(CC) -Wall -o $@ $^

setbuf_1: setbuf_1.c
	$(CC) -Wall -o $@ $^

fflush_1: fflush_1.c
	$(CC) -Wall -o $@ $^

vprintf_1: vprintf_1.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
